### ISSUE TITLE
&amp; being changed to &Amp;

### ISSUE THREAD

**Issue by jrbray1** [ppannuto/python-titlecase#40] opened 2019-02-21 18:03 UTC
I think you need to be cautious changing any strings that don't start with an alpha. For example while &amp; is valid &Amp; is not. Similarly parts of a title in quotes should be left alone

**Comment by ppannuto** [comment] 2019-02-21 18:13
I think this is really a duplicate of the problem raised in #38. In general, this library isn't really punctuation-aware. It'd be a nice enhancement, but not something I'll have time to attend to in the short term (though always happy to take PRs).

I'm closing this one as a dupe, but feel free to re-open if you disagree.

**Closed by ppannuto** 2019-02-21 18:13 UTC
